CREATE TABLE users (
    idUser SERIAL PRIMARY KEY,
    fullNameUser VARCHAR(255) NOT NULL,
    userName VARCHAR(155) NOT NULL,
    emailUser VARCHAR(155) NOT NULL UNIQUE,
    docId VARCHAR(155) NOT NULL UNIQUE,
    roleUser VARCHAR(100) NOT NULL,
    passwordUser VARCHAR(155) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
